# Generated by Django 4.0.4 on 2022-04-29 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raterprojectapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game_Category',
        ),
    ]
